// GENERATED FILE — do not edit by hand.
// Source: https://ancient.anguish.org/gameplay/accessiblemap.html
// Regenerate with: python3 scripts/compass/gen_locations.py

import '../models/known_location.dart';

/// Every named location on the official map, in map-room coordinates
/// centered on Tantallon (0, 0). x grows east, y grows north.
const List<KnownLocation> kKnownLocations = [
  KnownLocation('the orc caves', 'Orc caves', -7, 55, LocationKind.cave),
  KnownLocation('the igloo of the Snowfolk guild', 'Igloo of the Snowfolk guild', 3, 55, LocationKind.hall),
  KnownLocation('the yeti caves', 'Yeti caves', -14, 50, LocationKind.cave),
  KnownLocation('the Iceforge tunnels', 'Iceforge tunnels', -8, 50, LocationKind.cave),
  KnownLocation('home of the Iceforge clan', 'Home of the Iceforge clan', -7, 49, LocationKind.dwelling),
  KnownLocation('the Village of Caltisia', 'Caltisia', 3, 48, LocationKind.village),
  KnownLocation('the frost giant temple', 'Frost giant temple', -2, 44, LocationKind.temple),
  KnownLocation('Drute\'s tomb', 'Drute\'s tomb', -6, 43, LocationKind.ruin),
  KnownLocation('a bridge across the Sands river', 'Sands bridge', 10, 43, LocationKind.bridge),
  KnownLocation('the Shieldhand clan', 'Shieldhand clan', -12, 42, LocationKind.landmark),
  KnownLocation('the city of Norton', 'Norton', 11, 42, LocationKind.city),
  KnownLocation('the animal healer\'s camp', 'Animal healer\'s camp', 8, 41, LocationKind.camp),
  KnownLocation('Puffin Beach', 'Puffin Beach', 12, 40, LocationKind.coast),
  KnownLocation('a silent glen', 'Silent glen', 14, 39, LocationKind.nature),
  KnownLocation('the house of Gaius', 'House of Gaius', -7, 39, LocationKind.dwelling),
  KnownLocation('a bridge across the Natirar river', 'Natirar bridge', 8, 39, LocationKind.bridge),
  KnownLocation('the fallen paladins', 'Fallen paladins', -11, 38, LocationKind.landmark),
  KnownLocation('a hidden laboratory', 'Hidden laboratory', -15, 37, LocationKind.landmark),
  KnownLocation('the gremlin village', 'Gremlin village', 9, 37, LocationKind.village),
  KnownLocation('Seal Point', 'Seal Point', 15, 37, LocationKind.coast),
  KnownLocation('the gnoll temple', 'Gnoll temple', -3, 35, LocationKind.temple),
  KnownLocation('an island commune', 'Island commune', 16, 35, LocationKind.village),
  KnownLocation('the Kartini academy', 'Kartini academy', -10, 34, LocationKind.hall),
  KnownLocation('the frost giant steading', 'Frost giant steading', 3, 34, LocationKind.camp),
  KnownLocation('the ranger camp', 'Ranger camp', 7, 34, LocationKind.camp),
  KnownLocation('an entrance to the star caverns', 'Entrance to the star caverns', -13, 33, LocationKind.cave),
  KnownLocation('an entrance to the star caverns', 'Entrance to the star caverns', -11, 33, LocationKind.cave),
  KnownLocation('the besieged village of Brunswick', 'Besieged village of Brunswick', -16, 32, LocationKind.village),
  KnownLocation('an entrance to the star caverns', 'Entrance to the star caverns', -12, 32, LocationKind.cave),
  KnownLocation('the music man\'s dwelling', 'Music man\'s dwelling', -9, 32, LocationKind.dwelling),
  KnownLocation('a community with a missing princess', 'Community with a missing princess', -7, 30, LocationKind.village),
  KnownLocation('the thorp of Thranarack', 'Thranarack', -13, 29, LocationKind.village),
  KnownLocation('the troll\'s toll bridge across the river Levin', 'Troll\'s toll bridge across the river Levin', -1, 29, LocationKind.bridge),
  KnownLocation('the land of Zhamarr', 'Land of Zhamarr', -16, 27, LocationKind.landmark),
  KnownLocation('Andellen\'s encampment', 'Andellen\'s encampment', 4, 27, LocationKind.camp),
  KnownLocation('the portal to Harkke forest', 'Portal to Harkke forest', -6, 26, LocationKind.nature),
  KnownLocation('the city of Hobbitat', 'Hobbitat', 0, 26, LocationKind.city),
  KnownLocation('the village of Greenhaven', 'Greenhaven', -13, 25, LocationKind.village),
  KnownLocation('the Black Bear guild\'s den', 'Black Bear guild\'s den', -11, 25, LocationKind.hall),
  KnownLocation('the Andeli Castle', 'Andeli Castle', -9, 25, LocationKind.fortress),
  KnownLocation('an underground forest and temple', 'Underground forest and temple', -15, 23, LocationKind.temple),
  KnownLocation('the haunted shipwreck', 'Haunted shipwreck', 5, 23, LocationKind.ruin),
  KnownLocation('Burnham woods', 'Burnham woods', -3, 22, LocationKind.nature),
  KnownLocation('mount Kresh', 'Mount Kresh', -14, 21, LocationKind.nature),
  KnownLocation('the Tingi village', 'Tingi village', 4, 21, LocationKind.village),
  KnownLocation('the knight\'s stronghold', 'Knight\'s stronghold', -9, 20, LocationKind.fortress),
  KnownLocation('Zhou\'s weapon training camp', 'Zhou\'s weapon training camp', 1, 20, LocationKind.camp),
  KnownLocation('the flame pit', 'Flame pit', -12, 19, LocationKind.cave),
  KnownLocation('the hamlet of Arcadia', 'Arcadia', -5, 18, LocationKind.village),
  KnownLocation('Gralain\'s tomb', 'Gralain\'s tomb', -8, 16, LocationKind.ruin),
  KnownLocation('the fairy ring', 'Fairy ring', -1, 16, LocationKind.nature),
  KnownLocation('the historic Windom battlefield', 'Historic Windom battlefield', -10, 13, LocationKind.ruin),
  KnownLocation('the rock quarry', 'Rock quarry', -5, 13, LocationKind.cave),
  KnownLocation('the newbie academy of Leau and Drais', 'Newbie academy of Leau and Drais', -2, 12, LocationKind.hall),
  KnownLocation('Blor\'s tunnel stronghold', 'Blor\'s tunnel stronghold', -16, 11, LocationKind.cave),
  KnownLocation('fort Vaughn the brigands\' fortress', 'Fort Vaughn the brigands\' fortress', -10, 11, LocationKind.fortress),
  KnownLocation('a dragon cave', 'Dragon cave', -7, 10, LocationKind.cave),
  KnownLocation('the dwarven mines', 'Dwarven mines', -3, 10, LocationKind.cave),
  KnownLocation('the paladin hall', 'Paladin hall', 2, 10, LocationKind.hall),
  KnownLocation('Hopkin\'s garden', 'Hopkin\'s garden', 5, 10, LocationKind.farm),
  KnownLocation('the city of Nepeth', 'Nepeth', -6, 9, LocationKind.city),
  KnownLocation('Cyrano\'s beach house', 'Cyrano\'s beach house', 7, 9, LocationKind.dwelling),
  KnownLocation('queen Alisha\'s orphanage', 'Queen Alisha\'s orphanage', -4, 8, LocationKind.dwelling),
  KnownLocation('the village of Neville', 'Neville', 3, 8, LocationKind.village),
  KnownLocation('the village of Sadris', 'Sadris', -15, 7, LocationKind.village),
  KnownLocation('the chaos tower', 'Chaos tower', -10, 7, LocationKind.fortress),
  KnownLocation('Morin\'s farm', 'Morin\'s farm', -5, 7, LocationKind.farm),
  KnownLocation('a bridge across Snag creek', 'Snag creek bridge', -3, 7, LocationKind.bridge),
  KnownLocation('Alton\'s caverns', 'Alton\'s caverns', -13, 5, LocationKind.cave),
  KnownLocation('the orc king\'s mountain palace', 'Orc king\'s mountain palace', -11, 5, LocationKind.fortress),
  KnownLocation('a forsaken lighthouse', 'Forsaken lighthouse', 6, 5, LocationKind.coast),
  KnownLocation('the giants\' convention', 'Giants\' convention', -8, 4, LocationKind.landmark),
  KnownLocation('a windmill', 'Windmill', -4, 4, LocationKind.farm),
  KnownLocation('the Eastroad Inn', 'Eastroad Inn', 1, 4, LocationKind.dwelling),
  KnownLocation('the Djuvinder shipyard', 'Djuvinder shipyard', 4, 4, LocationKind.coast),
  KnownLocation('a bridge across the Lullingstone river', 'Lullingstone bridge', -13, 3, LocationKind.bridge),
  KnownLocation('an abandoned cottage', 'Abandoned cottage', -10, 3, LocationKind.ruin),
  KnownLocation('the city of Balan', 'Balan', -7, 3, LocationKind.city),
  KnownLocation('the city of Dalair', 'Dalair', -11, 2, LocationKind.city),
  KnownLocation('the goblin village of Ravel', 'Goblin village of Ravel', -8, 2, LocationKind.village),
  KnownLocation('a haunted manor', 'Haunted manor', 1, 2, LocationKind.ruin),
  KnownLocation('Anasazi village', 'Anasazi village', -15, 1, LocationKind.village),
  KnownLocation('Quildar\'s home', 'Quildar\'s home', -11, 1, LocationKind.dwelling),
  KnownLocation('the orc shaman\'s fortress', 'Orc shaman\'s fortress', -7, 1, LocationKind.fortress),
  KnownLocation('Fub\'s fortress', 'Fub\'s fortress', 1, 1, LocationKind.fortress),
  KnownLocation('the troll\'s den', 'Troll\'s den', -5, 0, LocationKind.cave),
  KnownLocation('a humpbacked bridge across snag creek', 'Snag creek bridge', -1, 0, LocationKind.bridge),
  KnownLocation('the city of Tantallon', 'Tantallon', 0, 0, LocationKind.city),
  KnownLocation('the Tantallon citypark', 'Tantallon citypark', -1, -1, LocationKind.landmark),
  KnownLocation('the Tantallon rescue station', 'Tantallon rescue station', 1, -1, LocationKind.landmark),
  KnownLocation('the orc slaver camp', 'Orc slaver camp', -16, -2, LocationKind.camp),
  KnownLocation('the Tantallon city dump', 'Tantallon city dump', 1, -3, LocationKind.landmark),
  KnownLocation('a rickety bridge across the lullingstone river', 'Lullingstone bridge', -14, -4, LocationKind.bridge),
  KnownLocation('an orc camp', 'Orc camp', -13, -4, LocationKind.camp),
  KnownLocation('an orc garden', 'Orc garden', -8, -5, LocationKind.farm),
  KnownLocation('the camp of the Scythe clan', 'Camp of the Scythe clan', -2, -5, LocationKind.camp),
  KnownLocation('Asyvan\'s evil temple', 'Asyvan\'s evil temple', -1, -5, LocationKind.temple),
  KnownLocation('the Hall of Heroes on the island of Cyprum', 'Hall of Heroes on the island of Cyprum', 11, -5, LocationKind.hall),
  KnownLocation('a thicket of bayberry bushes', 'Thicket of bayberry bushes', -10, -6, LocationKind.nature),
  KnownLocation('treasure beach on the island of Cyprum', 'Treasure beach on the island of Cyprum', 9, -6, LocationKind.coast),
  KnownLocation('Norich\'s ferry across the Lullingstone river', 'Norich\'s ferry across the Lullingstone river', -7, -8, LocationKind.bridge),
  KnownLocation('Oblivo\'s restaurant', 'Oblivo\'s restaurant', -1, -8, LocationKind.dwelling),
  KnownLocation('paladin palatial estates', 'Paladin palatial estates', -9, -9, LocationKind.dwelling),
  KnownLocation('home of Varys the numerologist', 'Home of Varys the numerologist', -15, -10, LocationKind.dwelling),
  KnownLocation('the nuns\' convent', 'Nuns\' convent', -12, -10, LocationKind.temple),
  KnownLocation('a small farmyard', 'Small farmyard', -6, -10, LocationKind.farm),
  KnownLocation('the monk monastery', 'Monk monastery', -2, -11, LocationKind.temple),
  KnownLocation('southeastern isle\'s Witchdoctor area', 'Southeastern isle\'s Witchdoctor area', 5, -11, LocationKind.coast),
  KnownLocation('the village of Duender', 'Duender', -17, -12, LocationKind.village),
  KnownLocation('the drow caverns', 'Drow caverns', -8, -13, LocationKind.cave),
  KnownLocation('Lord Merrick\'s ruined castle', 'Lord Merrick\'s ruined castle', 0, -13, LocationKind.ruin),
  KnownLocation('Endora\'s labyrinth', 'Endora\'s labyrinth', -13, -14, LocationKind.ruin),
  KnownLocation('a small house in the forest', 'Small house in the forest', -7, -14, LocationKind.dwelling),
  KnownLocation('the elven defense force camp', 'Elven defense force camp', -16, -15, LocationKind.camp),
  KnownLocation('the elven preserve', 'Elven preserve', -10, -16, LocationKind.nature),
  KnownLocation('the amazon castle on southeastern isle', 'Amazon castle on southeastern isle', 7, -17, LocationKind.fortress),
  KnownLocation('the village of Listan', 'Listan', -13, -18, LocationKind.village),
  KnownLocation('Zackwell\'s crypt', 'Zackwell\'s crypt', -15, -20, LocationKind.ruin),
  KnownLocation('the pearl diving beach', 'Pearl diving beach', 1, -20, LocationKind.coast),
  KnownLocation('the Ilderian encampment', 'Ilderian encampment', -17, -21, LocationKind.camp),
  KnownLocation('the treetop city of Sydryth', 'Treetop city of Sydryth', -8, -21, LocationKind.city),
  KnownLocation('the shapeshifter enclave', 'Shapeshifter enclave', -2, -22, LocationKind.landmark),
  KnownLocation('a garden', 'Garden', -12, -24, LocationKind.farm),
  KnownLocation('the wayfarer\'s rest', 'Wayfarer\'s rest', -3, -24, LocationKind.dwelling),
  KnownLocation('the manspider caves', 'Manspider caves', -9, -25, LocationKind.cave),
  KnownLocation('Gabaldon home of the druids', 'Gabaldon home of the druids', -16, -26, LocationKind.dwelling),
  KnownLocation('the mithril mountain mine', 'Mithril mountain mine', -8, -26, LocationKind.cave),
  KnownLocation('a silent grove', 'Silent grove', -17, -28, LocationKind.nature),
  KnownLocation('the shadow elf caves', 'Shadow elf caves', -10, -28, LocationKind.cave),
  KnownLocation('a secluded elven forest', 'Secluded elven forest', -16, -31, LocationKind.nature),
  KnownLocation('the knight retreat', 'Knight retreat', -8, -32, LocationKind.landmark),
  KnownLocation('the lizardmen village', 'Lizardmen village', -5, -32, LocationKind.village),
  KnownLocation('the rodentid temple excavation', 'Rodentid temple excavation', -8, -33, LocationKind.ruin),
  KnownLocation('the pass through Sadraq Range', 'Pass through Sadraq Range', -7, -33, LocationKind.landmark),
  KnownLocation('the island state of Alataciria', 'Alataciria', 3, -33, LocationKind.coast),
  KnownLocation('a prehistoric bog', 'Prehistoric bog', -1, -36, LocationKind.nature),
  KnownLocation('the city of Drakhiya', 'Drakhiya', -11, -37, LocationKind.city),
  KnownLocation('the azhad nomads\' camp', 'Azhad nomads\' camp', -9, -37, LocationKind.camp),
  KnownLocation('the glass blower', 'Glass blower', -10, -39, LocationKind.landmark),
  KnownLocation('the diamond monolith', 'Diamond monolith', -5, -39, LocationKind.temple),
  KnownLocation('the jaochi class hall', 'Jaochi class hall', 66, 50, LocationKind.hall),
  KnownLocation('an ex-cleric\'s hill', 'Ex-cleric\'s hill', 70, 45, LocationKind.landmark),
  KnownLocation('the community of Redcliff', 'Redcliff', 67, 31, LocationKind.village),
  KnownLocation('a bridge across the Enzed river', 'Enzed bridge', 74, 29, LocationKind.bridge),
  KnownLocation('Gwot\'s camp', 'Gwot\'s camp', 57, 24, LocationKind.camp),
  KnownLocation('fort mount wolf', 'Fort mount wolf', 67, 21, LocationKind.fortress),
  KnownLocation('a chinchilla farm', 'Chinchilla farm', 68, 18, LocationKind.farm),
  KnownLocation('the village of Fallan', 'Fallan', 63, 4, LocationKind.village),
  KnownLocation('ruins of a shrine', 'Ruins of a shrine', 66, 1, LocationKind.ruin),
  KnownLocation('the city of Gemynd', 'Gemynd', 52, -5, LocationKind.city),
  KnownLocation('a bridge across the Dunadan river', 'Dunadan bridge', 67, -6, LocationKind.bridge),
  KnownLocation('Ranor\'s Pride Inn', 'Ranor\'s Pride Inn', 52, -7, LocationKind.dwelling),
  KnownLocation('a bridge across the Vernon stream', 'Vernon stream bridge', 53, -7, LocationKind.bridge),
  KnownLocation('the Nehmar farm', 'Nehmar farm', 55, -7, LocationKind.farm),
  KnownLocation('an ancient dungeon', 'Ancient dungeon', 73, -8, LocationKind.ruin),
  KnownLocation('the seabird sanctuary', 'Seabird sanctuary', 50, -10, LocationKind.coast),
  KnownLocation('a drakon settlement', 'Drakon settlement', 73, -14, LocationKind.landmark),
  KnownLocation('the hamlet of the sunbird tribe', 'Hamlet of the sunbird tribe', 68, -20, LocationKind.village),
  KnownLocation('storm mountain', 'Storm mountain', 77, -20, LocationKind.landmark),
  KnownLocation('the factor\'s hut', 'Factor\'s hut', 51, -23, LocationKind.dwelling),
  KnownLocation('the thraxi hyf', 'Thraxi hyf', 72, -29, LocationKind.landmark),
  KnownLocation('the abandoned city of the eagle clan', 'Abandoned city of the eagle clan', 69, -37, LocationKind.ruin),
];
